#lang racket

(require "../utils/common.rkt")

(define (runtime) (current-inexact-milliseconds))

(define (prime? n)
  (define (smallest-divisor n)
    (define (find-divisor n test-divisor)
      (define (divides? a b) (= (remainder b a) 0))
      (cond
        ((> (square test-divisor) n) n)
        ((divides? test-divisor n) test-divisor)
        (else (find-divisor n (+ test-divisor 1)))
      )
    )
    (find-divisor n 2)
  )
  (= n (smallest-divisor n))
)

(define (timed-prime-test n)
  (define (start-prime-test n start-time)
    (define (report-prime elapsed-time)
      (display " *** ")
      (display elapsed-time)
    )
    ; (if (prime? n)
    (when (prime? n)
      (report-prime (- (runtime) start-time))
    )
  )
  ; (newline)
  (display n)
  (start-prime-test n (runtime))
  (newline)
)

; (define (search-for-primes start end n) (search-for-primes-iter start end n 0))
; (define (search-for-primes-iter start end n count)
;   (when (and (< start end) (< count n))
;     (if (and (prime? start) (timed-prime-test start))
;       (search-for-primes-iter (+ start 1) end n (+ count 1))
;       (search-for-primes-iter (+ start 1) end n count)
;     )
;   )
; )

; (search-for-primes 1000 1100 3)
; (search-for-primes 10000 10100 3)
; (search-for-primes 100000 100100 3)

(define (search-for-primes start end) (search-for-primes-iter (+ start (if (even? start) 1 0)) end))
(define (search-for-primes-iter start end)
  (when (and (< start end))
    (and (timed-prime-test start) (search-for-primes-iter (+ start 2) end))
  )
)

(search-for-primes 1000 1100)
(search-for-primes 10000 10100)
(search-for-primes 100000 100100)
